#!/usr/bin/perl
use strict;
use warnings;
use App::TextSieve;

my $app = App::TextSieve->new(patterns => [
    {
        name => "a_flood_of_warns",
        regex => qr/Not found ID=\d+. This program may be broken!/,
        duration => 120,
        max => 100,
    },
]);
$app->run;
